In [1]:
## Variables de entrada
a= 1.03
b=503
c= 2** 2
print("a= "+str(a)+" b= "+str(b)+" c= "+str(c))

a= 1.03 b= 503 c= 4


In [2]:
## Suma 
d= a+b
e= a+c
f= d+e-b
print("d= "+str(d)+" e= "+str(e)+" f= "+str(f))

d= 504.03 e= 5.03 f= 6.059999999999945


In [3]:
## Multiplicación 
ab= a*b
bc= b*c
g= f*(-a)
h= f/a
print("ab= "+str(ab)+" bc= "+str(bc)+" g= "+str(g)+" h= "+str(h))

ab= 518.09 bc= 2012 g= -6.241799999999944 h= 5.883495145631015


In [4]:
## Operaciones con vectores y matrices
#conda install -c anaconda numpy 

SyntaxError: invalid syntax (<ipython-input-4-7006905439eb>, line 2)

In [5]:
import numpy as np

A= [0,1,2,3,4,5]
B= np.zeros(6)
C= np.ones(6)
D= np.matrix([[0,1,2,3,4,5],[6,7,8,9,10,11]])
E= [[1,0],[0,1]]

In [9]:
# Suma
F= np.sum([0.5, 1.5])
G= np.sum([A,C])
print("A= "+str(A)+" B= "+str(B)+" C= "+str(C)+" D= "+str(D))
print("E= "+str(E)+" F= "+str(F)+" G= "+str(G))

A= [0, 1, 2, 3, 4, 5] B= [0. 0. 0. 0. 0. 0.] C= [1. 1. 1. 1. 1. 1.] D= [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
E= [[1, 0], [0, 1]] F= 2.0 G= 21.0


In [10]:
# Multiplicación
x1 = np.arange(9.0).reshape((3, 3))
print(x1)
x2 = np.arange(3.0)
print(x2)
np.multiply(x1, x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [8]:
# Producto punto
H = np.eye(2)
I = np.ones((2, 2)) * 2
J= H.dot(I)