## Single input

In [8]:
import numpy as np

number_of_toes= [8.5]
win_or_lose_binary= [1]
input= number_of_toes[0]
true= win_or_lose_binary[0]
weights= [0.1, 0.2, -0.1]
weight= weights[0]
#print(weight)
pred= np.multiply(input,weight)
error= (pred-true) ** 2
delta= pred-true
print("Input="+ str(input) + ", Weight=" + str(weight) +", Pred=" + str(pred) +", Error=" +str(error)+ ", Delta=" + str(delta))

Input=8.5, Weight=0.1, Pred=0.8500000000000001, Error=0.022499999999999975, Delta=-0.1499999999999999


## Multi input 

In [14]:
toes= [8.5, 9.5, 9.9, 9.0]
wlrec= [0.65, 0.8, 0.8, 0.9]
nfans= [1.2, 1.3, 0.5, 1.0]
win_or_lose_binary= [1,1,0,1]
true= win_or_lose_binary[0]

input= [toes[0], wlrec[0], nfans[0]]
pred= sum(np.multiply(input, weights))
error= (pred-true) ** 2
delta= pred-true

print("Input="+ str(input) + ", Weight=" + str(weights) +", Pred=" + str(pred) +", Error=" +str(error)+ ", Delta=" + str(delta))

Input=[8.5, 0.65, 1.2], Weight=[0.1, 0.2, -0.1], Pred=0.8600000000000001, Error=0.01959999999999997, Delta=-0.1399999999999999


## Single input- calculating weight of delta 

In [17]:
import numpy as np

def neural_network(input, weight):
    pred=input*weight
    return pred

In [25]:
number_of_toes= [8.5]
win_or_lose_binary= [1]

input= number_of_toes[0]
true= win_or_lose_binary[0]
print("Weight=" + str(weight))

pred= neural_network(input, weight)
pred2= np.multiply(input, weight)
error= (pred - true)** 2
delta= pred -  true
weight_delta= delta * input
print("Input=" + str(input) + ", Pred=" + str(pred) + ", Pred2=" + str(pred2) + ", Error=" + str(error) + ", Delta=" + str(delta) + ", Weight of delta=" + str(weight_delta))

Weight=0.1
Input=8.5, Pred=0.8500000000000001, Pred2=0.8500000000000001, Error=0.022499999999999975, Delta=-0.1499999999999999, Weight of delta=-1.2749999999999992


## Multi input- calculating weight of delta

In [49]:
def ele_mul(input, weight):
    output= np.multiply(input,weight)
    return output

def neural_network(input,weight):
    pred= np.ones(3)
    for i in range(3):
        pred = ele_mul(input,weight)
        return pred

In [68]:
input= [toes[0], wlrec[0], nfans[0]]
weights= [0.1, 0.2, -0.1]
weight= ([0.1] * np.ones(3))
print("Weight=" + str(weight) + ", Weights=" + str(weights))

pred= sum(neural_network(input, weights))
error= (pred-true) ** 2
delta= pred-true
delta= -delta
weight_deltas=ele_mul(delta, input)
print("Input=" + str(input) + ", Pred=" + str(pred) + ", Error=" + str(error) + ", Delta=" + str(delta) + ", Weight of delta=" + str(weight_deltas))

Weight=[0.1 0.1 0.1], Weights=[0.1, 0.2, -0.1]
Input=[8.5, 0.65, 1.2], Pred=0.8600000000000001, Error=0.01959999999999997, Delta=0.1399999999999999, Weight of delta=[1.19  0.091 0.168]


In [72]:
#Updating the weight
weights1= weights
alpha= (0.01 * np.ones(3))
weight_updated= np.multiply(weight_deltas, alpha)
weights3= weights1-weight_updated

print("Weight ini=" + str(weights1) + ", Alpha=" + str(alpha) + ", Weight of delta=" + str(weight_deltas) + ", Alpha * Weight of delta=" + str(weight_updated) + ", Current weights=" + str(weights3))

Weight ini=[0.1, 0.2, -0.1], Alpha=[0.01 0.01 0.01], Weight of delta=[1.19  0.091 0.168], Alpha * Weight of delta=[0.0119  0.00091 0.00168], Current weights=[ 0.0881   0.19909 -0.10168]


## Resumen (Pag. 88)

In [80]:
toes= [8.5, 9.5, 9.9, 9.0]
wlrec= [0.65, 0.8, 0.8, 0.9]
nfans= [1.2, 1.3, 0.5, 1.0]

win_or_lose_binary= [1,1,0,1]
true= win_or_lose_binary[0]
alpha= 0.01
weights= [0.1, 0.2, -0.1]
input= [toes[0], wlrec[0], nfans[0]]

In [81]:
def ele_mul(input, weight):
    output= np.multiply(input,weight)
    return output

def neural_network(input,weight):
    pred= np.ones(3)
    for i in range(3):
        pred = sum(ele_mul(input,weight))
        return pred

In [82]:
for iter in range(3):
    pred= neural_network(input, weights)
    error= (pred-true) ** 2
    delta= pred - true
    weight_deltas= ele_mul(input, delta)
    
    print(" ")
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("Weights:" + str(weights))
    print("Weights of delta:")
    print(str(weight_deltas))
    print
    
    for i in range(len(weights)):
        weights[i] -= np.multiply(alpha, weight_deltas[i])
    

 
Iteration:1
Pred:0.8600000000000001
Error:0.01959999999999997
Delta:-0.1399999999999999
Weights:[0.1, 0.2, -0.1]
Weights of delta:
[-1.19  -0.091 -0.168]
 
Iteration:2
Pred:0.9637574999999999
Error:0.0013135188062500048
Delta:-0.036242500000000066
Weights:[0.1119, 0.20091, -0.09832]
Weights of delta:
[-0.30806125 -0.02355763 -0.043491  ]
 
Iteration:3
Pred:0.9906177228125002
Error:8.802712522307997e-05
Delta:-0.009382277187499843
Weights:[0.11498061250000001, 0.20114557625, -0.09788509000000001]
Weights of delta:
[-0.07974936 -0.00609848 -0.01125873]


## Resumen (Pag. 90)

In [88]:
alpha= 0.3
weights=[0.1, 0.2, -0.1]
input=[toes[0], wlrec[0], nfans[0]]

for iter in range(3):
    pred= neural_network(input, weights)
    error= (pred-true)** 2
    delta= pred-true
    weight_deltas= ele_mul(input, delta)
    #weight_deltas[0]= 0
    
    print(" ")
    print("Iteration:" + str(iter+1))
    print("Pred:" + str(pred))
    print("Error:" + str(error))
    print("Delta:" + str(delta))
    print("Weights:" + str(weights))
    print("Weights of delta:")
    print(str(weight_deltas))
    print
    
    for i in range(len(weights)):
        weights[i] -= np.multiply(alpha, weight_deltas[i])

 
Iteration:1
Pred:0.8600000000000001
Error:0.01959999999999997
Delta:-0.1399999999999999
Weights:[0.1, 0.2, -0.1]
Weights of delta:
[-1.19  -0.091 -0.168]
 
Iteration:2
Pred:3.972724999999998
Error:8.837093925624988
Delta:2.972724999999998
Weights:[0.45699999999999974, 0.2273, -0.04960000000000005]
Weights of delta:
[25.2681625   1.93227125  3.56727   ]
 
Iteration:3
Pred:-62.12209946874995
Error:3984.3994413427627
Delta:-63.12209946874995
Weights:[-7.123448749999994, -0.3523813749999995, -1.1197809999999992]
Weights of delta:
[-536.53784548  -41.02936465  -75.74651936]


# Gradient descent learning with multiple outputs

In [121]:
weights= [0.3, 0.2, 0.9]
wlrec= [0.65, 1.0, 1.0, 0.9]
hurt= [0.1, 0.0, 0.0, 0.1]
win= [1,1,0,1]
sad= [0.1, 0.0, 0.1, 0.2]

input= wlrec[0]
true= [hurt[0], win[0], sad[0]]

def neural_network(input, weights):
    pred= np.multiply(input, weights)
    return pred

In [122]:
pred= (neural_network(input, weights))
print("Prediction= " + str(pred))

Prediction= [0.195 0.13  0.585]


In [126]:
error= [0,0,0]
delta= [0,0,0]
weights2= np.ones(3)

for i in range(len(true)):
    error[i]= (pred[i] - true[i] )** 2
    delta[i]= pred[i] - true[i]
    weight_deltas[i]= np.multiply(input, weights[i])
    weights2[i]= weights[i] - (weight_deltas[i] * 0.1)

In [128]:
print("Input= " + str(input) + ", Weights= " + str(weights) + ", Pred= " + str(pred) + ", Error= " + str(error) + ", Delta= " + str(delta) + ", Weight of delta= " + str(weight_deltas) + ", Weights update= " + str(weights2))

    

Input= 0.65, Weights= [0.3, 0.2, 0.9], Pred= [0.195 0.13  0.585], Error= [0.009025, 0.7569, 0.2352250000000001], Delta= [0.095, -0.87, 0.4850000000000001], Weight of delta= [0.195 0.13  0.585], Weights update= [0.2805 0.187  0.8415]


# Gradient descent with multiple inputs and outputs

In [187]:
weights= np.array([[0.1, 0.1, -0.3], #hurt?
         [0.1, 0.2, 0.0], #win?
         [0.0, 1.3, 0.1]]) #sad?

toes= np.array([8.5, 9.5, 9.9, 9.0])
wlrec= np.array([0.65, 0.8, 0.8, 0.9])
nfans= np.array([1.2, 1.3, 0.5, 1.0])
hurt= [0.1, 0.0, 0.0, 0.1]
win= [1,1,0,1]
sad= [0.1, 0.0, 0.1, 0.2]
alpha= 0.01

input= np.array([toes[0], wlrec[0], nfans[0]])
true= np.array([hurt[0], win[0], sad[0]])


In [188]:
#print("Input= "+ str(input)+"Weights= "+ str(weights))
#prod= np.ones(3)
#for i in range(3):
 #   prod[i]= np.dot(input, weights[i])
#print(weights[i], prod)

In [189]:
#def neural_network(input, weights):
 #   pred= np.ones(3)
  #  for i in range(3):
   #     pred[i]= np.dot(input, weights[i])
    #    return pred

In [190]:
#pred= neural_network(input, weights)
pred= np.ones(3)
for i in range(3):
    pred[i]= np.dot(input, weights[i])

error= [0,0,0]
delta= [0,0,0]

for i in range(len(true)):
    error[i]= (pred[i] - true[i]) ** 2
    delta[i]= pred[i] - true[i]
          
print("Input= " + str(input) + ", Prediction= " + str(pred) + ", Error= " + str(error) + ", Delta= " + str(delta))

Input= [8.5  0.65 1.2 ], Prediction= [0.555 0.98  0.965], Error= [0.20702500000000007, 0.0003999999999999963, 0.7482250000000001], Delta= [0.45500000000000007, -0.019999999999999907, 0.8650000000000001]


In [191]:
weight_delta= np.multiply(input, delta)
weight_update= weights - (weight_delta*alpha) 

print("Weight of delta= "+str(weight_delta) + ", Weight update= "+ str(weight_update))

Weight of delta= [ 3.8675 -0.013   1.038 ], Weight update= [[ 0.061325  0.10013  -0.31038 ]
 [ 0.061325  0.20013  -0.01038 ]
 [-0.038675  1.30013   0.08962 ]]


In [192]:
#Otro procedimiento

def outer_prod(vec_a, vec_b):
    out= np.ones((len(vec_a), len(vec_b)))
    for i in range(len(vec_a)):
        for j in range(len(vec_b)):
            out[i][j]= vec_a[i]*vec_b[j]
            return out

In [193]:
weight_deltas= outer_prod(input, delta)

for i in range(len(weights)):
    for j in range(len(weights[0])):
        weights[i][j] -= alpha * (weight_deltas[i][j])
        
        print("Weight of deltas= "+str(weight_deltas)+", Weights= "+str(weights))

Weight of deltas= [[3.8675 1.     1.    ]
 [1.     1.     1.    ]
 [1.     1.     1.    ]], Weights= [[ 0.061325  0.1      -0.3     ]
 [ 0.1       0.2       0.      ]
 [ 0.        1.3       0.1     ]]
Weight of deltas= [[3.8675 1.     1.    ]
 [1.     1.     1.    ]
 [1.     1.     1.    ]], Weights= [[ 0.061325  0.09     -0.3     ]
 [ 0.1       0.2       0.      ]
 [ 0.        1.3       0.1     ]]
Weight of deltas= [[3.8675 1.     1.    ]
 [1.     1.     1.    ]
 [1.     1.     1.    ]], Weights= [[ 0.061325  0.09     -0.31    ]
 [ 0.1       0.2       0.      ]
 [ 0.        1.3       0.1     ]]
Weight of deltas= [[3.8675 1.     1.    ]
 [1.     1.     1.    ]
 [1.     1.     1.    ]], Weights= [[ 0.061325  0.09     -0.31    ]
 [ 0.09      0.2       0.      ]
 [ 0.        1.3       0.1     ]]
Weight of deltas= [[3.8675 1.     1.    ]
 [1.     1.     1.    ]
 [1.     1.     1.    ]], Weights= [[ 0.061325  0.09     -0.31    ]
 [ 0.09      0.19      0.      ]
 [ 0.        1.3       0.1   