# Classic version

In [12]:
clear all

In [13]:
ih_wgt= [[0.1, 0.2, -0.1], #hid[0]
        [-0.1, 0.1, 0.9], #hid[1]
        [0.1, 0.4, 0.1]] #hid[2]

In [14]:
hp_wgt= [[0.3, 1.1, -0.3], #hurt?
        [0.1, 0.2, 0.0], #win?
        [0.0, 1.3, 0.1]] #sad?

In [15]:
weights= [ih_wgt, hp_wgt]

In [16]:
def neural_network(input, weights):
    hid= vect_mat_mul (input, weights[0])
    pred= vect_mat_mul (hid, weights[1])
    return pred

In [17]:
def vect_mat_mul(vect, matrix):
    output= np.zeros(len(vect))
    assert(len(vect) == len(matrix))
    for i in range(vect):
        output[i] = w_sum(vect, matrix[i])
    return output

In [18]:
def w_sum(a,b):
    #assert(len(a) == len(b))
    #output = 0
    for i in range(3):
        #output += (a[i] * b[i]) 
        output [i] += np.dot (a[i], b)
    return output

In [19]:
toes= [8.5, 9.5, 9.9, 9.0]
wlrec= [0.65, 0.8, 0.8, 0.9]
nfans= [1.2, 1.3, 0.5, 1.0]

In [20]:
#input corresponds to every entry
input= [toes[0], wlrec[0], nfans[0]]


In [21]:
pred= neural_network(input, weights)

TypeError: 'list' object cannot be interpreted as an integer

# Numpy version

In [22]:
import numpy as np

In [23]:
#toes %win #fans
ih_wgt= np.array([
    [0.1, 0.2, -0.1], #hid[0]
    [-0.1, 0.1, 0.9], #hid[1]
    [0.1, 0.4, 0.1]]).T #hid[2]

In [24]:
#hid[0] hid[1] hid[2]
hp_wgt= np.array([
    [0.3, 1.1, -0.3],#hurt?
    [0.1, 0.2, 0.0],#win?
    [0.0, 1.3, 0.1]]).T#sad?

In [25]:
weights= [ih_wgt, hp_wgt]

In [26]:
def neural_network(input, weights):
    hid= input.dot(weights[0])
    pred= hid.dot(weights[1])
    return pred

In [27]:
toes= np.array([8.5, 9.5, 9.9, 9.0])
wlrec= np.array([0.65, 0.8, 0.8, 0.9])
nfans= np.array([1.2, 1.3, 0.5, 1.0])

In [31]:
input= np.array([toes[0], wlrec[0], nfans[0]])
pred= neural_network(input, weights)
print(pred)

[0.2135 0.145  0.5065]


## Numpy

In [32]:
a= np.array([0,1,2,3])

In [33]:
print(a)

[0 1 2 3]


In [34]:
print(a*0.1)

[0.  0.1 0.2 0.3]


In [39]:
b= np.array([[0,1,2,3],[0,0,1,1],[1,1,3,3],[2,2,4,4]])

In [40]:
print(b)

[[0 1 2 3]
 [0 0 1 1]
 [1 1 3 3]
 [2 2 4 4]]


In [41]:
print(a*b)

[[ 0  1  4  9]
 [ 0  0  2  3]
 [ 0  1  6  9]
 [ 0  2  8 12]]


In [42]:
c= np.array([[0,0,0,0],[1,1,1,1]])
print(c)

[[0 0 0 0]
 [1 1 1 1]]


In [43]:
print(a*c)

[[0 0 0 0]
 [0 1 2 3]]


In [45]:
A= np.zeros((1,4))#vector of length 4
B= np.zeros((4,3))#matrix 4 rows and 3 columns
C= A.dot(B)
#D= B.dot(A)

In [46]:
print(C.shape)

(1, 3)


In [47]:
print(C)

[[0. 0. 0.]]


## Compare

In [48]:
knob_weight= 0.5
input= 0.5
goal_pred= 0.8
pred= input* knob_weight
error= (pred - goal_pred) ** 2
print(error)

0.30250000000000005


## Error - Hot and cold

### Predict

In [69]:
weight= 0.1

In [70]:
lr= 0.01

In [71]:
def neural_network(input, weight):
    prediction= input*weight
    return prediction

In [72]:
number_of_toes= [8.5]
win_or_lose_binary= [1] ##// (won!!!)
input= number_of_toes[0]
true=win_or_lose_binary[0]
pred= neural_network(input, weight)
error= (pred-true) ** 2

In [73]:
print(weight)

0.1


In [74]:
print(error)

0.022499999999999975


### Compare

In [75]:
lr= 0.01
p_up= neural_network(input, weight + lr)
e_up= (p_up - true) ** 2

In [76]:
p_dn= neural_network (input, weight - lr)
e_dn= (p_dn - true) ** 2

In [77]:
print(e_up)
print(e_dn)

0.004224999999999993
0.05522499999999994


## Compare + Learn

In [78]:
if (error > e_dn or error > e_up): ## Sustitui || por or    
    if(e_dn < e_up):
        weight -= lr
        
        if(e_up < e_up):
            weight += lr

In [79]:
print(weight)

0.1


In [80]:
print(error)

0.022499999999999975
